### ISSUE TITLE
 Property 'end' in type 'ResourceStream<T>' is not assignable to the same property in base type 'Transform'.

### ISSUE THREAD

**Issue by prabhatmishra-metro** [googleapis/nodejs-bigquery#1075]
Dear Team,

Facing the below issue, while we build our nodejs application.

> tsc --p ./tsconfig.json

node_modules/@google-cloud/paginator/build/src/resource-stream.d.ts:37:5 - error TS2416: Property 'end' in type 'ResourceStream<T>' is not assignable to the same property in base type 'Transform'.
  Type '(...args: any[]) => void' is not assignable to type '{ (cb?: () => void): this; (chunk: any, cb?: () => void): this; (chunk: any, encoding?: BufferEncoding, cb?: () => void): this; }'.
    Type 'void' is not assignable to type 'this'.
      'this' could be instantiated with an arbitrary type which could be unrelated to 'void'.

37     end(...args: any[]): void;

#### Environment details

  - OS: MacOS BigSur v11.6.2    (same issue in windows10 as well)
  - Node.js version: v16.0.0
  - npm version: 7.10.0
  - `@google-cloud/bigquery` version: 5.10.0
  - typescript  : 3.9.10
  - @google-cloud/paginator: 3.0.6
  - ts-node: 8.10.2

#### Steps to reproduce

  1. Build the application

Thanks!

**Comment by prabhatmishra-metro** [comment]
fixed the issue using this reference https://github.com/grpc/grpc-node/issues/2002

**Comment by JarnoRFB** [comment]
I still get this error with version `5.12.0` using node `v16.14.0` and @types/node `^16.11.26`. @prabhatmishra-metro what did you exactly do to get around this error?

**Comment by prabhatmishra-metro** [comment]
`@types/node": "14.18.3` Fixed the version and did `npm install` again

**Comment by JarnoRFB** [comment]
Thanks, downgrading `@types/node` led to other type errors, but running `npm upgrade @google-cloud/paginator` could resolve the issue.
